# Generated by Django 4.0.6 on 2022-08-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0002_rename_noticia_comentarioevento_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestacomentarioevento',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='respuestacomentarioevento',
            name='comentario',
        ),
        migrations.DeleteModel(
            name='ComentarioEvento',
        ),
        migrations.DeleteModel(
            name='RespuestaComentarioEvento',
        ),
    ]
