# Generated by Django 4.0.6 on 2022-09-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0003_remove_respuestacomentarioevento_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='modalidad_evento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
