# Generated by Django 4.0.6 on 2022-08-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0005_alter_noticia_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.ManyToManyField(to='noticias_app.categoria'),
        ),
    ]
